// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace real_time_producer
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;

	public partial class ActorItem : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"ActorItem\",\"namespace\":\"Classes\",\"fields\":[{\"name\":\"ncon" +
				"st\",\"type\":\"string\"},{\"name\":\"birthyear\",\"type\":\"int\"},{\"name\":\"title_count\",\"ty" +
				"pe\":\"int\"},{\"name\":\"votes_avg\",\"type\":\"double\"},{\"name\":\"rating_avg\",\"type\":\"dou" +
				"ble\"},{\"name\":\"is_adult\",\"type\":\"double\"},{\"name\":\"release_year_min\",\"type\":\"int" +
				"\"},{\"name\":\"release_year_max\",\"type\":\"int\"},{\"name\":\"release_year_avg\",\"type\":\"d" +
				"ouble\"},{\"name\":\"title_type_movie\",\"type\":\"double\"},{\"name\":\"title_type_short\",\"" +
				"type\":\"double\"},{\"name\":\"title_type_tv_episode\",\"type\":\"double\"},{\"name\":\"title_" +
				"type_tv_mini_series\",\"type\":\"double\"},{\"name\":\"title_type_tv_movie\",\"type\":\"doub" +
				"le\"},{\"name\":\"title_type_tv_series\",\"type\":\"double\"},{\"name\":\"title_type_tv_shor" +
				"t\",\"type\":\"double\"},{\"name\":\"title_type_tv_special\",\"type\":\"double\"},{\"name\":\"ti" +
				"tle_type_video\",\"type\":\"double\"},{\"name\":\"title_type_video_game\",\"type\":\"double\"" +
				"},{\"name\":\"role_category_actor\",\"type\":\"double\"},{\"name\":\"role_category_archive_" +
				"footage\",\"type\":\"double\"},{\"name\":\"role_category_archive_sound\",\"type\":\"double\"}" +
				",{\"name\":\"role_category_cinematographer\",\"type\":\"double\"},{\"name\":\"role_category" +
				"_composer\",\"type\":\"double\"},{\"name\":\"role_category_director\",\"type\":\"double\"},{\"" +
				"name\":\"role_category_editor\",\"type\":\"double\"},{\"name\":\"role_category_producer\",\"" +
				"type\":\"double\"},{\"name\":\"role_category_production_designer\",\"type\":\"double\"},{\"n" +
				"ame\":\"role_category_self\",\"type\":\"double\"},{\"name\":\"role_category_writer\",\"type\"" +
				":\"double\"},{\"name\":\"genre_action\",\"type\":\"double\"},{\"name\":\"genre_adult\",\"type\":" +
				"\"double\"},{\"name\":\"genre_adventure\",\"type\":\"double\"},{\"name\":\"genre_animation\",\"" +
				"type\":\"double\"},{\"name\":\"genre_biography\",\"type\":\"double\"},{\"name\":\"genre_comedy" +
				"\",\"type\":\"double\"},{\"name\":\"genre_crime\",\"type\":\"double\"},{\"name\":\"genre_documen" +
				"tary\",\"type\":\"double\"},{\"name\":\"genre_drama\",\"type\":\"double\"},{\"name\":\"genre_fam" +
				"ily\",\"type\":\"double\"},{\"name\":\"genre_fantasy\",\"type\":\"double\"},{\"name\":\"genre_fi" +
				"lm_noir\",\"type\":\"double\"},{\"name\":\"genre_game_show\",\"type\":\"double\"},{\"name\":\"ge" +
				"nre_history\",\"type\":\"double\"},{\"name\":\"genre_horror\",\"type\":\"double\"},{\"name\":\"g" +
				"enre_music\",\"type\":\"double\"},{\"name\":\"genre_musical\",\"type\":\"double\"},{\"name\":\"g" +
				"enre_mystery\",\"type\":\"double\"},{\"name\":\"genre_news\",\"type\":\"double\"},{\"name\":\"ge" +
				"nre_reality_tv\",\"type\":\"double\"},{\"name\":\"genre_romance\",\"type\":\"double\"},{\"name" +
				"\":\"genre_sci_fi\",\"type\":\"double\"},{\"name\":\"genre_short\",\"type\":\"double\"},{\"name\"" +
				":\"genre_sport\",\"type\":\"double\"},{\"name\":\"genre_talk_show\",\"type\":\"double\"},{\"nam" +
				"e\":\"genre_thriller\",\"type\":\"double\"},{\"name\":\"genre_war\",\"type\":\"double\"},{\"name" +
				"\":\"genre_western\",\"type\":\"double\"}]}");
		private string _nconst;
		private int _birthyear;
		private int _title_count;
		private double _votes_avg;
		private double _rating_avg;
		private double _is_adult;
		private int _release_year_min;
		private int _release_year_max;
		private double _release_year_avg;
		private double _title_type_movie;
		private double _title_type_short;
		private double _title_type_tv_episode;
		private double _title_type_tv_mini_series;
		private double _title_type_tv_movie;
		private double _title_type_tv_series;
		private double _title_type_tv_short;
		private double _title_type_tv_special;
		private double _title_type_video;
		private double _title_type_video_game;
		private double _role_category_actor;
		private double _role_category_archive_footage;
		private double _role_category_archive_sound;
		private double _role_category_cinematographer;
		private double _role_category_composer;
		private double _role_category_director;
		private double _role_category_editor;
		private double _role_category_producer;
		private double _role_category_production_designer;
		private double _role_category_self;
		private double _role_category_writer;
		private double _genre_action;
		private double _genre_adult;
		private double _genre_adventure;
		private double _genre_animation;
		private double _genre_biography;
		private double _genre_comedy;
		private double _genre_crime;
		private double _genre_documentary;
		private double _genre_drama;
		private double _genre_family;
		private double _genre_fantasy;
		private double _genre_film_noir;
		private double _genre_game_show;
		private double _genre_history;
		private double _genre_horror;
		private double _genre_music;
		private double _genre_musical;
		private double _genre_mystery;
		private double _genre_news;
		private double _genre_reality_tv;
		private double _genre_romance;
		private double _genre_sci_fi;
		private double _genre_short;
		private double _genre_sport;
		private double _genre_talk_show;
		private double _genre_thriller;
		private double _genre_war;
		private double _genre_western;
		public virtual Schema Schema
		{
			get
			{
				return ActorItem._SCHEMA;
			}
		}
		public string nconst
		{
			get
			{
				return this._nconst;
			}
			set
			{
				this._nconst = value;
			}
		}
		public int birthyear
		{
			get
			{
				return this._birthyear;
			}
			set
			{
				this._birthyear = value;
			}
		}
		public int title_count
		{
			get
			{
				return this._title_count;
			}
			set
			{
				this._title_count = value;
			}
		}
		public double votes_avg
		{
			get
			{
				return this._votes_avg;
			}
			set
			{
				this._votes_avg = value;
			}
		}
		public double rating_avg
		{
			get
			{
				return this._rating_avg;
			}
			set
			{
				this._rating_avg = value;
			}
		}
		public double is_adult
		{
			get
			{
				return this._is_adult;
			}
			set
			{
				this._is_adult = value;
			}
		}
		public int release_year_min
		{
			get
			{
				return this._release_year_min;
			}
			set
			{
				this._release_year_min = value;
			}
		}
		public int release_year_max
		{
			get
			{
				return this._release_year_max;
			}
			set
			{
				this._release_year_max = value;
			}
		}
		public double release_year_avg
		{
			get
			{
				return this._release_year_avg;
			}
			set
			{
				this._release_year_avg = value;
			}
		}
		public double title_type_movie
		{
			get
			{
				return this._title_type_movie;
			}
			set
			{
				this._title_type_movie = value;
			}
		}
		public double title_type_short
		{
			get
			{
				return this._title_type_short;
			}
			set
			{
				this._title_type_short = value;
			}
		}
		public double title_type_tv_episode
		{
			get
			{
				return this._title_type_tv_episode;
			}
			set
			{
				this._title_type_tv_episode = value;
			}
		}
		public double title_type_tv_mini_series
		{
			get
			{
				return this._title_type_tv_mini_series;
			}
			set
			{
				this._title_type_tv_mini_series = value;
			}
		}
		public double title_type_tv_movie
		{
			get
			{
				return this._title_type_tv_movie;
			}
			set
			{
				this._title_type_tv_movie = value;
			}
		}
		public double title_type_tv_series
		{
			get
			{
				return this._title_type_tv_series;
			}
			set
			{
				this._title_type_tv_series = value;
			}
		}
		public double title_type_tv_short
		{
			get
			{
				return this._title_type_tv_short;
			}
			set
			{
				this._title_type_tv_short = value;
			}
		}
		public double title_type_tv_special
		{
			get
			{
				return this._title_type_tv_special;
			}
			set
			{
				this._title_type_tv_special = value;
			}
		}
		public double title_type_video
		{
			get
			{
				return this._title_type_video;
			}
			set
			{
				this._title_type_video = value;
			}
		}
		public double title_type_video_game
		{
			get
			{
				return this._title_type_video_game;
			}
			set
			{
				this._title_type_video_game = value;
			}
		}
		public double role_category_actor
		{
			get
			{
				return this._role_category_actor;
			}
			set
			{
				this._role_category_actor = value;
			}
		}
		public double role_category_archive_footage
		{
			get
			{
				return this._role_category_archive_footage;
			}
			set
			{
				this._role_category_archive_footage = value;
			}
		}
		public double role_category_archive_sound
		{
			get
			{
				return this._role_category_archive_sound;
			}
			set
			{
				this._role_category_archive_sound = value;
			}
		}
		public double role_category_cinematographer
		{
			get
			{
				return this._role_category_cinematographer;
			}
			set
			{
				this._role_category_cinematographer = value;
			}
		}
		public double role_category_composer
		{
			get
			{
				return this._role_category_composer;
			}
			set
			{
				this._role_category_composer = value;
			}
		}
		public double role_category_director
		{
			get
			{
				return this._role_category_director;
			}
			set
			{
				this._role_category_director = value;
			}
		}
		public double role_category_editor
		{
			get
			{
				return this._role_category_editor;
			}
			set
			{
				this._role_category_editor = value;
			}
		}
		public double role_category_producer
		{
			get
			{
				return this._role_category_producer;
			}
			set
			{
				this._role_category_producer = value;
			}
		}
		public double role_category_production_designer
		{
			get
			{
				return this._role_category_production_designer;
			}
			set
			{
				this._role_category_production_designer = value;
			}
		}
		public double role_category_self
		{
			get
			{
				return this._role_category_self;
			}
			set
			{
				this._role_category_self = value;
			}
		}
		public double role_category_writer
		{
			get
			{
				return this._role_category_writer;
			}
			set
			{
				this._role_category_writer = value;
			}
		}
		public double genre_action
		{
			get
			{
				return this._genre_action;
			}
			set
			{
				this._genre_action = value;
			}
		}
		public double genre_adult
		{
			get
			{
				return this._genre_adult;
			}
			set
			{
				this._genre_adult = value;
			}
		}
		public double genre_adventure
		{
			get
			{
				return this._genre_adventure;
			}
			set
			{
				this._genre_adventure = value;
			}
		}
		public double genre_animation
		{
			get
			{
				return this._genre_animation;
			}
			set
			{
				this._genre_animation = value;
			}
		}
		public double genre_biography
		{
			get
			{
				return this._genre_biography;
			}
			set
			{
				this._genre_biography = value;
			}
		}
		public double genre_comedy
		{
			get
			{
				return this._genre_comedy;
			}
			set
			{
				this._genre_comedy = value;
			}
		}
		public double genre_crime
		{
			get
			{
				return this._genre_crime;
			}
			set
			{
				this._genre_crime = value;
			}
		}
		public double genre_documentary
		{
			get
			{
				return this._genre_documentary;
			}
			set
			{
				this._genre_documentary = value;
			}
		}
		public double genre_drama
		{
			get
			{
				return this._genre_drama;
			}
			set
			{
				this._genre_drama = value;
			}
		}
		public double genre_family
		{
			get
			{
				return this._genre_family;
			}
			set
			{
				this._genre_family = value;
			}
		}
		public double genre_fantasy
		{
			get
			{
				return this._genre_fantasy;
			}
			set
			{
				this._genre_fantasy = value;
			}
		}
		public double genre_film_noir
		{
			get
			{
				return this._genre_film_noir;
			}
			set
			{
				this._genre_film_noir = value;
			}
		}
		public double genre_game_show
		{
			get
			{
				return this._genre_game_show;
			}
			set
			{
				this._genre_game_show = value;
			}
		}
		public double genre_history
		{
			get
			{
				return this._genre_history;
			}
			set
			{
				this._genre_history = value;
			}
		}
		public double genre_horror
		{
			get
			{
				return this._genre_horror;
			}
			set
			{
				this._genre_horror = value;
			}
		}
		public double genre_music
		{
			get
			{
				return this._genre_music;
			}
			set
			{
				this._genre_music = value;
			}
		}
		public double genre_musical
		{
			get
			{
				return this._genre_musical;
			}
			set
			{
				this._genre_musical = value;
			}
		}
		public double genre_mystery
		{
			get
			{
				return this._genre_mystery;
			}
			set
			{
				this._genre_mystery = value;
			}
		}
		public double genre_news
		{
			get
			{
				return this._genre_news;
			}
			set
			{
				this._genre_news = value;
			}
		}
		public double genre_reality_tv
		{
			get
			{
				return this._genre_reality_tv;
			}
			set
			{
				this._genre_reality_tv = value;
			}
		}
		public double genre_romance
		{
			get
			{
				return this._genre_romance;
			}
			set
			{
				this._genre_romance = value;
			}
		}
		public double genre_sci_fi
		{
			get
			{
				return this._genre_sci_fi;
			}
			set
			{
				this._genre_sci_fi = value;
			}
		}
		public double genre_short
		{
			get
			{
				return this._genre_short;
			}
			set
			{
				this._genre_short = value;
			}
		}
		public double genre_sport
		{
			get
			{
				return this._genre_sport;
			}
			set
			{
				this._genre_sport = value;
			}
		}
		public double genre_talk_show
		{
			get
			{
				return this._genre_talk_show;
			}
			set
			{
				this._genre_talk_show = value;
			}
		}
		public double genre_thriller
		{
			get
			{
				return this._genre_thriller;
			}
			set
			{
				this._genre_thriller = value;
			}
		}
		public double genre_war
		{
			get
			{
				return this._genre_war;
			}
			set
			{
				this._genre_war = value;
			}
		}
		public double genre_western
		{
			get
			{
				return this._genre_western;
			}
			set
			{
				this._genre_western = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.nconst;
			case 1: return this.birthyear;
			case 2: return this.title_count;
			case 3: return this.votes_avg;
			case 4: return this.rating_avg;
			case 5: return this.is_adult;
			case 6: return this.release_year_min;
			case 7: return this.release_year_max;
			case 8: return this.release_year_avg;
			case 9: return this.title_type_movie;
			case 10: return this.title_type_short;
			case 11: return this.title_type_tv_episode;
			case 12: return this.title_type_tv_mini_series;
			case 13: return this.title_type_tv_movie;
			case 14: return this.title_type_tv_series;
			case 15: return this.title_type_tv_short;
			case 16: return this.title_type_tv_special;
			case 17: return this.title_type_video;
			case 18: return this.title_type_video_game;
			case 19: return this.role_category_actor;
			case 20: return this.role_category_archive_footage;
			case 21: return this.role_category_archive_sound;
			case 22: return this.role_category_cinematographer;
			case 23: return this.role_category_composer;
			case 24: return this.role_category_director;
			case 25: return this.role_category_editor;
			case 26: return this.role_category_producer;
			case 27: return this.role_category_production_designer;
			case 28: return this.role_category_self;
			case 29: return this.role_category_writer;
			case 30: return this.genre_action;
			case 31: return this.genre_adult;
			case 32: return this.genre_adventure;
			case 33: return this.genre_animation;
			case 34: return this.genre_biography;
			case 35: return this.genre_comedy;
			case 36: return this.genre_crime;
			case 37: return this.genre_documentary;
			case 38: return this.genre_drama;
			case 39: return this.genre_family;
			case 40: return this.genre_fantasy;
			case 41: return this.genre_film_noir;
			case 42: return this.genre_game_show;
			case 43: return this.genre_history;
			case 44: return this.genre_horror;
			case 45: return this.genre_music;
			case 46: return this.genre_musical;
			case 47: return this.genre_mystery;
			case 48: return this.genre_news;
			case 49: return this.genre_reality_tv;
			case 50: return this.genre_romance;
			case 51: return this.genre_sci_fi;
			case 52: return this.genre_short;
			case 53: return this.genre_sport;
			case 54: return this.genre_talk_show;
			case 55: return this.genre_thriller;
			case 56: return this.genre_war;
			case 57: return this.genre_western;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.nconst = (System.String)fieldValue; break;
			case 1: this.birthyear = (System.Int32)fieldValue; break;
			case 2: this.title_count = (System.Int32)fieldValue; break;
			case 3: this.votes_avg = (System.Double)fieldValue; break;
			case 4: this.rating_avg = (System.Double)fieldValue; break;
			case 5: this.is_adult = (System.Double)fieldValue; break;
			case 6: this.release_year_min = (System.Int32)fieldValue; break;
			case 7: this.release_year_max = (System.Int32)fieldValue; break;
			case 8: this.release_year_avg = (System.Double)fieldValue; break;
			case 9: this.title_type_movie = (System.Double)fieldValue; break;
			case 10: this.title_type_short = (System.Double)fieldValue; break;
			case 11: this.title_type_tv_episode = (System.Double)fieldValue; break;
			case 12: this.title_type_tv_mini_series = (System.Double)fieldValue; break;
			case 13: this.title_type_tv_movie = (System.Double)fieldValue; break;
			case 14: this.title_type_tv_series = (System.Double)fieldValue; break;
			case 15: this.title_type_tv_short = (System.Double)fieldValue; break;
			case 16: this.title_type_tv_special = (System.Double)fieldValue; break;
			case 17: this.title_type_video = (System.Double)fieldValue; break;
			case 18: this.title_type_video_game = (System.Double)fieldValue; break;
			case 19: this.role_category_actor = (System.Double)fieldValue; break;
			case 20: this.role_category_archive_footage = (System.Double)fieldValue; break;
			case 21: this.role_category_archive_sound = (System.Double)fieldValue; break;
			case 22: this.role_category_cinematographer = (System.Double)fieldValue; break;
			case 23: this.role_category_composer = (System.Double)fieldValue; break;
			case 24: this.role_category_director = (System.Double)fieldValue; break;
			case 25: this.role_category_editor = (System.Double)fieldValue; break;
			case 26: this.role_category_producer = (System.Double)fieldValue; break;
			case 27: this.role_category_production_designer = (System.Double)fieldValue; break;
			case 28: this.role_category_self = (System.Double)fieldValue; break;
			case 29: this.role_category_writer = (System.Double)fieldValue; break;
			case 30: this.genre_action = (System.Double)fieldValue; break;
			case 31: this.genre_adult = (System.Double)fieldValue; break;
			case 32: this.genre_adventure = (System.Double)fieldValue; break;
			case 33: this.genre_animation = (System.Double)fieldValue; break;
			case 34: this.genre_biography = (System.Double)fieldValue; break;
			case 35: this.genre_comedy = (System.Double)fieldValue; break;
			case 36: this.genre_crime = (System.Double)fieldValue; break;
			case 37: this.genre_documentary = (System.Double)fieldValue; break;
			case 38: this.genre_drama = (System.Double)fieldValue; break;
			case 39: this.genre_family = (System.Double)fieldValue; break;
			case 40: this.genre_fantasy = (System.Double)fieldValue; break;
			case 41: this.genre_film_noir = (System.Double)fieldValue; break;
			case 42: this.genre_game_show = (System.Double)fieldValue; break;
			case 43: this.genre_history = (System.Double)fieldValue; break;
			case 44: this.genre_horror = (System.Double)fieldValue; break;
			case 45: this.genre_music = (System.Double)fieldValue; break;
			case 46: this.genre_musical = (System.Double)fieldValue; break;
			case 47: this.genre_mystery = (System.Double)fieldValue; break;
			case 48: this.genre_news = (System.Double)fieldValue; break;
			case 49: this.genre_reality_tv = (System.Double)fieldValue; break;
			case 50: this.genre_romance = (System.Double)fieldValue; break;
			case 51: this.genre_sci_fi = (System.Double)fieldValue; break;
			case 52: this.genre_short = (System.Double)fieldValue; break;
			case 53: this.genre_sport = (System.Double)fieldValue; break;
			case 54: this.genre_talk_show = (System.Double)fieldValue; break;
			case 55: this.genre_thriller = (System.Double)fieldValue; break;
			case 56: this.genre_war = (System.Double)fieldValue; break;
			case 57: this.genre_western = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
